from z3 import *
s1 = Solver()
s2 = Solver()
x = Int('x')
y = Int('y')

s1.add(x>3,x<7)
print("Initial smt")
print(s2.to_smt2())
s2.push()
for c in s1.assertions():
    s2.add(c)
print("smt after adding constraint")
print(s2.to_smt2())
s2.check()
s2.push()
s2.add(y<10,x>0)
s2.check()
s2.pop()
print('final smt: ')
print(s2.to_smt2())